import { useEffect, useRef } from 'react'
import { Link } from 'react-router-dom'

export default function AITeaser() {
  const containerRef = useRef(null)

  useEffect(() => {
    const el = containerRef.current
    if (!el) return
    let t = 0
    const id = setInterval(() => {
      t += 1
      const bubbles = el.querySelectorAll('[data-float]')
      bubbles.forEach((b, i) => {
        const offset = Math.sin((t + i * 10) / 18) * 4
        b.style.transform = `translateY(${offset}px)`
      })
    }, 1000 / 30)
    return () => clearInterval(id)
  }, [])

  const Bubble = ({ role = 'user', children, delay = 0 }) => (
    <div
      data-float
      style={{
        alignSelf: role === 'user' ? 'flex-end' : 'flex-start',
        background: role === 'user'
          ? 'linear-gradient(135deg, rgba(59,130,246,0.18), rgba(59,130,246,0.28))'
          : 'linear-gradient(135deg, rgba(16,185,129,0.18), rgba(16,185,129,0.28))',
        color: 'var(--text)',
        border: '1px solid rgba(255,255,255,0.15)',
        borderRadius: 14,
        padding: '10px 12px',
        maxWidth: 520,
        boxShadow: '0 10px 24px rgba(0,0,0,0.18)',
        animation: `popIn 480ms ease ${delay}ms both`
      }}
    >
      {children}
    </div>
  )

  return (
    <div ref={containerRef} style={{
      position: 'relative',
      border: '1px solid rgba(255,255,255,0.1)',
      background: 'linear-gradient(135deg, rgba(59,130,246,0.06), rgba(147,51,234,0.06))',
      borderRadius: 20,
      padding: 20,
      overflow: 'hidden'
    }}>
      <style>{`
        @keyframes popIn { 0% { opacity: 0; transform: translateY(6px) scale(0.98); } 100% { opacity: 1; transform: translateY(0) scale(1); } }
        @keyframes shimmerLine { 0% { background-position: -200% 0 } 100% { background-position: 200% 0 } }
      `}</style>
      <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 10 }}>
        <div style={{ width: 32, height: 32, borderRadius: 999, background: 'linear-gradient(135deg,#22d3ee,#3b82f6)', boxShadow: '0 6px 14px rgba(0,0,0,0.25)' }} />
        <div style={{ fontWeight: 800 }}>Ask AI: How can I improve my resume?</div>
        <div style={{ marginLeft: 'auto' }}>
          <Link to="/chatbot" className="cta-primary" style={{ padding: '8px 12px' }}>Open Assistant ↗</Link>
        </div>
      </div>

      <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
        <Bubble role="user" delay={80}>
          I’m a fresher in Computer Science. How do I make my resume stand out?
        </Bubble>
        <Bubble role="assistant" delay={160}>
          Focus the top third on impact: a crisp 2–3 line summary, a skills block tailored to the role, and a featured project with metrics.
        </Bubble>
        <Bubble role="assistant" delay={240}>
          Example: “Built a React app with 1.2k users; cut page load by 35%.” Numbers pop.
        </Bubble>
        <Bubble role="user" delay={320}>
          Should I include hackathons?
        </Bubble>
        <Bubble role="assistant" delay={400}>
          Yes—list top 1–2 with a one-line win or what you shipped. Treat them like micro-experience.
        </Bubble>
      </div>

      {/* Shimmer footer */}
      <div style={{
        marginTop: 14,
        fontSize: 12,
        color: 'var(--muted)',
        display: 'flex',
        alignItems: 'center',
        gap: 8
      }}>
        <div style={{
          width: 120,
          height: 8,
          borderRadius: 999,
          background: 'linear-gradient(90deg, rgba(255,255,255,0.05), rgba(255,255,255,0.18), rgba(255,255,255,0.05))',
          backgroundSize: '200% 100%',
          animation: 'shimmerLine 2.2s ease infinite'
        }} />
        Smart tips generated by AI
      </div>
    </div>
  )
}




